export enum ERouteTable {
  ROOT = '/',
  SIGIN_IN = '/sign-in',
  SIGIN_UP = '/sign-up',
  VERIFY_ACCOUNT = '/verify-account',
  FORGOT_PASSWORD = '/forgot-password',
  CHANGE_PASSWORD = '/change-password',
  HOME = '/home',
  ONBOARDING = '/onboarding',
  DETAIL_LESSON = '/detail-lesson',
  QUESTION_SCREEN = '/question-screen',
  SETTING_SCREEN = '/settings',
  LEARN_CHESS = '/learn-chess',
  ABOUT_US = '/about-us',
  EDIT_NAME = '/edit-name',
  RESET_PASSWORD = '/reset-password',
  SUPPORT = '/support',
  PRACTICE_CHESS = '/practice-chess',
  PRACTICE_CHILDREN = '/practice-children',
  QUIZ_START = '/quiz-start',
  RESULT_CHESS = '/result-chess',
}
